<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body class='bg-dark container'>

    <?php if ($this->request->has('location')) {
        echo "<pre>";
        $currentLocation = $this->request->get('location');
        echo "</pre>";
    ?>

        <div class="row container">
            <div class="col-4 my-2 bg-warning  d-flex justify-content-center p-5" style="height:200px">
                <p class="row text-light h2">
                    <?php echo $currentLocation;
                    ?>
                </p>
            </div>
            <div class="col-4">
                <div class="row">
                    <?php echo $this->tag->linkTo(["location/currentWeather?location=$currentLocation", 'Current Weather', 'class' => 'btn mt-2 btn-primary mx-5']); ?>
                </div>
                <div class="row">
                    <?php echo $this->tag->linkTo(["location/forecast?location=$currentLocation", 'Forecast', 'class' => 'btn  mt-4 btn-danger mx-5']); ?>
                </div>
              
                <div class="row">
                    <?php echo $this->tag->linkTo(["location/airQuality?location=$currentLocation", 'Air Quality', 'class' => 'btn mt-4 btn-success mx-5']); ?>
                </div>
            </div>
            <div class="col-4">
                <div class="row">
                    <?php echo $this->tag->linkTo(["location/timezone?location=$currentLocation", 'Time Zone', 'class' => 'btn mt-2 btn-info mx-5']); ?>
                </div>
                <div class="row">
                    <?php echo $this->tag->linkTo(["location/sports?location=$currentLocation", 'Sports', 'class' => 'btn mt-4 btn-success mx-5']); ?>
                </div>
                <div class="row">
                    <?php echo $this->tag->linkTo(["location/?astronomy=$currentLocation", 'Astronomy', 'class' => 'btn mt-4 btn-light mx-5']); ?>
                </div>
                <div class="row">
                    <?php echo $this->tag->linkTo(["location/weatherAlerts?location=$currentLocation", 'Weather Alerts', 'class' => 'btn mt-4 btn-warning mx-5']); ?>
                </div>
            </div>
        </div>
        <hr class="mt-5">
        <?php
        echo "<pre>";
        // print_r($location);
        echo "</pre>"; ?>
        <div class="row p-4" style="background-color:#66CDA3">
            <div class="col-12">
                <div class="row h3 text-light">
                    Weather in <?php echo $location->location['name'] ?> , <?php echo $location->location['region'] ?>
                </div>
                <div class="progress" style="height: 1px;">
                    <div class="progress-bar" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <div class="row h2 mt-4 text-light">
                    <?php echo $location->current['temp_c'] ?> &#x2103; | <?php echo $location->current['temp_f'] ?> &#x2109; &nbsp;
                    <span class="text-info"> <?php echo $location->current['condition']['text'] ?> </span>
                </div>
                <div class="row h4 mt-4 text-light">

                    <div class="col-6">
                        <div class="row my-4">
                            <div class="col-6">
                                Humidity
                            </div>
                            <div class="col-6">
                                <?php echo $location->current['humidity'] ?>%
                            </div>
                        </div>
                        <div class="row my-4">
                            <div class="col-6">
                                Wind
                            </div>
                            <div class="col-6">
                                <?php echo $location->current['wind_kph'] ?> Km/hr
                            </div>
                        </div>
                        <div class="row my-4">
                            <div class="col-6">
                                Pressure
                            </div>
                            <div class="col-6">
                                <?php echo $location->current['pressure_mb'] ?> mb
                            </div>
                        </div>
                        <div class="row my-4">
                            <div class="col-6">
                                Precipitation
                            </div>
                            <div class="col-6">
                                <?php echo $location->current['precip_mm'] ?> mm
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="row my-4">
                            <div class="col-6">
                                Cloud
                            </div>
                            <div class="col-6">
                                <?php echo $location->current['cloud'] ?>
                            </div>
                        </div>
                        <div class="row my-4">
                            <div class="col-6">
                                UV Index
                            </div>
                            <div class="col-6">
                                <?php echo $location->current['uv'] ?> of 10
                            </div>
                        </div>
                        <div class="row my-4">
                            <div class="col-6">
                                Feels Like
                            </div>
                            <div class="col-6">
                                <?php echo $location->current['feelslike_c'] ?> &#x2103; | <?php echo $location->current['feelslike_f'] ?> &#x2109;
                            </div>
                        </div>
                        <div class="row my-4">
                            <div class="col-6">
                                Gust
                            </div>
                            <div class="col-6">
                                <?php echo $location->current['gust_kph'] ?> Km/hr
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>


    <?php  } ?>

</body>

</html>