<?php
header("Cache-Control: no cache");
session_cache_limiter("private_no_expire");
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body class='container bg-dark'>

    <!-- -------------------------------------------Form for location --------------------------------------->

    <?php echo $this->tag->form(['', 'class' => 'my-4 container text-center  p-4 border']); ?>
    <p class="row">
        <label for="email" class='label col-2 mx-5 h4 text-bold text-light'>Location</label>
        <?php echo $this->tag->textField(['location', 'class' => 'form-control col-6']) ?>
        <?php echo $this->tag->submitButton(['Get Location', 'class' => 'btn  btn-primary mx-5']); ?>
    </p>
    <p>

    </p>
    <?php echo $this->tag->endForm(); ?>
    <!-- -----------------------------------------------------Form ends -------------------------------------------------->

        <?php if (isset($locations)) {
            // echo "<pre>";
            // print_r($locations);
            // echo "</pre>";
        ?>
            
            <table class="table table-dark table-striped mt-3">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Region</th>
                        <th scope="col">Country</th>
                        <th scope="col">Weather</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($locations as $location) { ?>

                    <tr>
                        <th scope="row"><?php echo $location['name'] ?></th>
                        <td><?php echo $location['region'] ?></td>
                        <td><?php echo $location['country'] ?></td>
                        <td><?php echo $this->tag->linkTo(["index/currentLocation?location=$location[name]",'Weather', 'class' => 'btn  btn-primary mx-5']); ?></td>
                    </tr>

            <?php }
            } ?>
    </tbody>
    </table>
</body>

</html>