<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
   
</head>

<body class="bg-dark mt-5 container">
    <div class="row p-4" style="background-color:#66CDA3">
        <div class="col-12">
            <div class="row h3 text-light">
                Astronomy in <?php echo $location->location['name'] ?> , <?php echo $location->location['region'] ?>
            </div>
            <div class="progress" style="height: 1px;">
                <div class="progress-bar" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
         
            <div class="row h4 mt-4 text-light">
                <div class="col-6">
                    <div class="row my-4">
                        <div class="col-6">
                           Sunrise
                        </div>
                        <div class="col-6">
                            <?php echo $location->astronomy['astro']['sunrise'] ?>
                        </div>
                    </div>
                    <div class="row my-4">
                        <div class="col-6">
                            Sunset
                        </div>
                        <div class="col-6">
                            <?php echo $location->astronomy['astro']['sunset'] ?>
                        </div>
                    </div>
                    <div class="row my-4">
                        <div class="col-6">
                        Moonrise
                        </div>
                        <div class="col-6">
                            <?php echo $location->astronomy['astro']['moonrise'] ?>
                        </div>
                    </div>
                    <div class="row my-4">
                        <div class="col-6">
                        Moonset
                        </div>
                        <div class="col-6">
                            <?php echo $location->astronomy['astro']['moonset'] ?>
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="row my-4">
                        <div class="col-6">
                        Moon Phase
                        </div>
                        <div class="col-6">
                            <?php echo $location->astronomy['astro']['moon_phase'] ?>
                        </div>
                    </div>
                    <div class="row my-4">
                        <div class="col-6">
                        Moon Illumination
                        </div>
                        <div class="col-6">
                            <?php echo $location->astronomy['astro']['moon_illumination'] ?>
                        </div>
                    </div>
                
                </div>
            </div>
        </div>
    </div>
</body>

</html>